//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ltq_Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ltq_Monhoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ltq_Monhoc()
        {
            this.Ltq_Ketqua = new HashSet<Ltq_Ketqua>();
        }
    
        public string LtqMaMH { get; set; }
        public string LtqTenMH { get; set; }
        public Nullable<int> LtqSotiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ltq_Ketqua> Ltq_Ketqua { get; set; }
    }
}
