//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ltq_Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ltq_SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ltq_SinhVien()
        {
            this.Ltq_Ketqua = new HashSet<Ltq_Ketqua>();
        }
    
        public string LtqMaSV { get; set; }
        public string LtqHoSV { get; set; }
        public string LtqTenSV { get; set; }
        public Nullable<bool> LtqPhai { get; set; }
        public Nullable<System.DateTime> LtqNgaySinh { get; set; }
        public string LtqNoiSinh { get; set; }
        public string LtqMaKH { get; set; }
        public Nullable<double> LtqHocBong { get; set; }
        public Nullable<double> LtqDiemTrungBinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ltq_Ketqua> Ltq_Ketqua { get; set; }
        public virtual ltqKhoa ltqKhoa { get; set; }
    }
}
