//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ltq_Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ltq_Ketqua
    {
        public string LtqMaSV { get; set; }
        public string LtqMaMH { get; set; }
        public string LtqDiem { get; set; }
    
        public virtual Ltq_Monhoc Ltq_Monhoc { get; set; }
        public virtual Ltq_SinhVien Ltq_SinhVien { get; set; }
    }
}
