//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ltq_Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ltqKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ltqKhoa()
        {
            this.Ltq_SinhVien = new HashSet<Ltq_SinhVien>();
        }
    
        public string LtqMaKH { get; set; }
        public string LtqTenKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ltq_SinhVien> Ltq_SinhVien { get; set; }
    }
}
