//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtqBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ltqKhoa
    {
        public string LtqMaKH { get; set; }
        public string LtqtenKH { get; set; }
        public Nullable<bool> LtqTrangThai { get; set; }
    }
}
