//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtqBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LtqCNTT2Lesson07DbEntities : DbContext
    {
        public LtqCNTT2Lesson07DbEntities()
            : base("name=LtqCNTT2Lesson07DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ltqKhoa> ltqKhoa { get; set; }
        public virtual DbSet<ltqSinhVien> ltqSinhVien { get; set; }
    }
}
