//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtqBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ltqSinhVien
    {
        public string LtqMaSV { get; set; }
        public string LtqHoSV { get; set; }
        public string LtqTenSV { get; set; }
        public Nullable<System.DateTime> LtqNgaySinh { get; set; }
        public Nullable<bool> LtqPhai { get; set; }
        public string LtqPhone { get; set; }
        public string LtqEmail { get; set; }
        public string LtqMaKH { get; set; }
    }
}
